x-airflow-common: &airflow-common
  build: .
  # image: goodnews724/kowork-scaper-arm:latest
  # platform: linux/arm64
  env_file:
    - ./.env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=30
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW_UID=50000
    - AIRFLOW_GID=0
    - GOOGLE_SHEET_KEY=${GOOGLE_SHEET_KEY}
    - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    - TOP5000COMPANY_URL=${TOP5000COMPANY_URL}
    # Airflow 관리자 계정 자동 생성
    - _AIRFLOW_WWW_USER_USERNAME=admin
    - _AIRFLOW_WWW_USER_PASSWORD=admin123
    - _AIRFLOW_WWW_USER_EMAIL=admin@example.com
    - _AIRFLOW_WWW_USER_FIRSTNAME=Admin
    - _AIRFLOW_WWW_USER_LASTNAME=User
    - _AIRFLOW_WWW_USER_ROLE=Admin
  volumes:
    - ./src:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./key:/opt/airflow/key
    - ./data:/opt/airflow/data
  user: "50000:0"
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:13
    platform: linux/arm64
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    platform: linux/arm64
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-webserver:
    <<: *airflow-common
    command: bash -c "airflow db init && airflow users create --username admin --password admin123 --firstname Admin --lastname User --role Admin --email admin@example.com || true && airflow webserver"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname $(hostname)"]
      interval: 30s
      timeout: 30s
      retries: 5

volumes:
  postgres-db: